"""
OSINT--N | Module: Report Generator
Saves results as JSON, CSV, and a styled HTML report.
"""

import json
import csv
import os
from datetime import datetime
from pathlib import Path
from rich.console import Console

console = Console()

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>OSINT--N Report | {module} | {target}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: 'Courier New', monospace;
    background: #0d1117;
    color: #c9d1d9;
    padding: 2rem;
  }}
  header {{
    border-bottom: 2px solid #21262d;
    padding-bottom: 1.5rem;
    margin-bottom: 2rem;
  }}
  header h1 {{ color: #58a6ff; font-size: 1.8rem; letter-spacing: 2px; }}
  header p  {{ color: #8b949e; margin-top: .4rem; font-size: .9rem; }}
  .badge {{
    display: inline-block;
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 4px;
    padding: .2rem .7rem;
    font-size: .8rem;
    margin-right: .5rem;
    color: #58a6ff;
  }}
  .card {{
    background: #161b22;
    border: 1px solid #21262d;
    border-radius: 8px;
    margin-bottom: 2rem;
    overflow: hidden;
  }}
  .card-header {{
    background: #21262d;
    padding: .8rem 1.2rem;
    font-size: 1rem;
    font-weight: bold;
    color: #58a6ff;
    letter-spacing: 1px;
    text-transform: uppercase;
  }}
  table {{
    width: 100%;
    border-collapse: collapse;
  }}
  td {{
    padding: .6rem 1.2rem;
    border-bottom: 1px solid #21262d;
    font-size: .88rem;
  }}
  tr:last-child td {{ border-bottom: none; }}
  td:first-child {{
    color: #e3b341;
    width: 35%;
    font-weight: bold;
  }}
  td:last-child {{ color: #c9d1d9; word-break: break-all; }}
  .found   {{ color: #3fb950; font-weight: bold; }}
  .missing {{ color: #f85149; }}
  footer {{
    margin-top: 3rem;
    border-top: 1px solid #21262d;
    padding-top: 1rem;
    color: #8b949e;
    font-size: .8rem;
    text-align: center;
  }}
</style>
</head>
<body>
<header>
  <h1>⚡ OSINT--N Report</h1>
  <p>
    <span class="badge">Module: {module}</span>
    <span class="badge">Target: {target}</span>
    <span class="badge">{timestamp}</span>
  </p>
</header>

<div class="card">
  <div class="card-header">🔍 Findings</div>
  <table>
    {rows}
  </table>
</div>

<footer>Generated by OSINT--N &nbsp;|&nbsp; github.com/EdisonDushku1/OSINT--N &nbsp;|&nbsp; For authorized use only.</footer>
</body>
</html>"""


def save(data: dict, config: dict):
    if not config["general"].get("save_results", True):
        return

    out_dir = Path(config["general"]["output_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)

    target    = str(data.get("target", "unknown")).replace("@", "_at_").replace(".", "_").replace("/", "_")
    module    = data.get("module", "scan")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base      = f"{module}_{target}_{timestamp}"
    formats   = config["general"].get("export_formats", ["json"])

    saved = []

    # JSON
    if "json" in formats:
        p = out_dir / f"{base}.json"
        with open(p, "w") as f:
            json.dump(data, f, indent=2, default=str)
        saved.append(str(p))

    # CSV
    if "csv" in formats:
        p = out_dir / f"{base}.csv"
        flat = {str(k): str(v) for k, v in data.items()}
        with open(p, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=flat.keys())
            writer.writeheader()
            writer.writerow(flat)
        saved.append(str(p))

    # HTML
    if "html" in formats:
        p = out_dir / f"{base}.html"
        rows = ""
        for k, v in data.items():
            if k == "module":
                continue
            val_class = ""
            val       = str(v) if v else "N/A"
            if "found" in k.lower() and str(v).lower() in ("true", "yes"):
                val_class = "found"
            elif val == "N/A":
                val_class = "missing"
            rows += f'<tr><td>{k}</td><td class="{val_class}">{val}</td></tr>\n'

        html = HTML_TEMPLATE.format(
            module=module.upper(),
            target=data.get("target", "unknown"),
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            rows=rows
        )
        p.write_text(html, encoding="utf-8")
        saved.append(str(p))

    for s in saved:
        console.print(f"  [dim green]✔ Saved → {s}[/dim green]")
